import type { Metadata } from 'next';
import './globals.css';
import { SystemContextProvider } from '@context/useSystem';
import { ContactContextProvider } from '@context/useContact';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SystemContextProvider>
      <ContactContextProvider>
        <html lang="en">
          <body>{children}</body>
        </html>
      </ContactContextProvider>
    </SystemContextProvider>
  );
}
