# Generated by Django 5.0.6 on 2024-07-03 04:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('language', models.CharField(max_length=100, verbose_name='Idioma')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino')], max_length=10, verbose_name='Gênero')),
                ('birthdate', models.DateField(verbose_name='Data de Nascimento')),
                ('avatar', models.ImageField(default='default_user.webp', null=True, upload_to='')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
