# Generated by Django 5.0.6 on 2024-06-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_avatar_alter_contact_gender_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
