# Generated by Django 5.0.6 on 2024-06-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_contact_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(default='default_user.webp', null=True, upload_to=''),
        ),
    ]
