# Generated by Django 5.0.6 on 2024-06-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contact_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='language',
            field=models.CharField(default='English', max_length=100, verbose_name='Idioma'),
            preserve_default=False,
        ),
    ]
