# Generated by Django 5.0.6 on 2024-07-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_contact_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(choices=[('male', 'Masculino'), ('female', 'Feminino')], max_length=10, verbose_name='Gênero'),
        ),
    ]
