# Generated by Django 5.0.6 on 2024-07-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_alter_contact_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='avatar',
        ),
        migrations.AddField(
            model_name='contact',
            name='avatar_file',
            field=models.ImageField(blank=True, default='default_user.webp', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
