# Generated by Django 5.0.6 on 2024-07-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_remove_contact_avatar_contact_avatar_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='avatar_file',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='contact',
            name='avatar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Avatar'),
        ),
    ]
