# Generated by Django 5.0.6 on 2024-07-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_remove_contact_avatar_file_remove_contact_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(default='default_user.webp', null=True, upload_to=''),
        ),
    ]
